# Generated by Django 2.1.5 on 2019-02-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('spAttack', models.IntegerField()),
                ('spDefence', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('isMegaEvolution', models.BooleanField()),
                ('types', models.CharField(max_length=255)),
                ('evolutions', models.CharField(max_length=255)),
                ('abilities', models.CharField(max_length=255)),
                ('hiddenAbilities', models.CharField(max_length=255)),
                ('form', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
