# Generated by Django 2.1.5 on 2019-02-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_data_viewer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemondata',
            name='form',
            field=models.CharField(default='', max_length=255),
        ),
    ]
